# Generated by Django 4.1.5 on 2023-01-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='job_description',
            field=models.TextField(default='Описание профессии'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='job_title',
            field=models.CharField(default='Название профессии', max_length=100),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='thematic_img',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
