# Generated by Django 4.1.5 on 2023-01-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_mainpage_job_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='thematic_img',
            field=models.ImageField(default='', upload_to='img/'),
        ),
    ]
