# Generated by Django 4.1.5 on 2023-01-16 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_statisticsskillsbyyear_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearAnalysisSkillStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='skill',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.yearanalysisskillstatistics'),
        )
    ]
