# Generated by Django 4.1.5 on 2023-01-16 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_yearanalysisskillstatistics_alter_skill_year_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatisticsSkillsByYear',
        ),
    ]
