# Generated by Django 4.1.5 on 2023-01-17 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_statisticsskillsbyyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество повторений навыка за определенный год')),
                ('name_skill', models.CharField(max_length=50, verbose_name='Название навыка')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ('-year_statistics',),
            },
        ),
        migrations.AlterModelOptions(
            name='yearanalysisskillstatistics',
            options={'ordering': ('-year_statistics',), 'verbose_name': 'Год для выбора ТОП-10 навыков', 'verbose_name_plural': 'Годы для выбора ТОП-10 навыков'},
        ),
        migrations.RemoveField(
            model_name='yearanalysisskillstatistics',
            name='year',
        ),
        migrations.AddField(
            model_name='yearanalysisskillstatistics',
            name='graphic_title',
            field=models.CharField(default='', max_length=100, verbose_name='Название графика'),
        ),
        migrations.AddField(
            model_name='yearanalysisskillstatistics',
            name='statistics_graph_skills_by_year_img',
            field=models.ImageField(default='', upload_to='img/top_10_skills_by_year/'),
        ),
        migrations.AddField(
            model_name='yearanalysisskillstatistics',
            name='year_statistics',
            field=models.IntegerField(default=1970, verbose_name='Год статистики'),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='skillbyyear',
            name='year_statistics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='main.yearanalysisskillstatistics'),
        ),
    ]
