# Generated by Django 4.1.5 on 2023-01-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_skillbyyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearanalysisskillstatistics',
            name='graphic_title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Название графика'),
        ),
        migrations.AlterField(
            model_name='yearanalysisskillstatistics',
            name='statistics_graph_skills_by_year_img',
            field=models.ImageField(blank=True, default='', upload_to='img/top_10_skills_by_year/'),
        ),
        migrations.AlterField(
            model_name='yearanalysisskillstatistics',
            name='year_statistics',
            field=models.IntegerField(default='1970', verbose_name='Год статистики'),
        ),
    ]
