# Generated by Django 4.1.5 on 2023-01-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_yearanalysisskillstatistics_graphic_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearanalysisskillstatistics',
            name='year_statistics',
            field=models.IntegerField(default=1970, verbose_name='Год статистики'),
        ),
    ]
