# Generated by Django 4.1.5 on 2023-01-17 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_yearanalysisskillstatistics_year_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillbyyear',
            name='year_statistics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='main.yearanalysisskillstatistics', verbose_name='Год актуальности данных'),
        ),
    ]
