# Generated by Django 4.1.5 on 2023-01-18 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_exchangerate_vacanciesdifcurrencies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerate',
            name='RUR',
        ),
    ]
