# Generated by Django 4.1.5 on 2023-01-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_exchangerate_rur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='BYR',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='EUR',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='KZT',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='UAH',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='USD',
            field=models.FloatField(),
        ),
    ]
