# Generated by Django 4.1.5 on 2023-01-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_exchangerate_byr_alter_exchangerate_eur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacanciesdifcurrencies',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
