# Generated by Django 4.1.5 on 2023-01-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_vacanciesdifcurrencies_salary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillbyyear',
            options={'ordering': ('count',), 'verbose_name': 'Ститистика по навыку за все время', 'verbose_name_plural': 'Ститистики по навыкам за все время'},
        ),
        migrations.AlterField(
            model_name='yearanalysisskillstatistics',
            name='statistics_graph_skills_by_year_img',
            field=models.ImageField(blank=True, default='', upload_to='img/top_10_skills_by_year/', verbose_name='График в формате изображения'),
        ),
    ]
