# Generated by Django 4.1.5 on 2023-01-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_skillbyyear_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistic_graph_title', models.CharField(default='', max_length=100, verbose_name='Название графика')),
                ('statistic_graph_img', models.ImageField(blank=True, default='', upload_to='img/statistics_graphs/', verbose_name='График в формате изображения')),
            ],
            options={
                'verbose_name': 'График статистики',
                'verbose_name_plural': 'Графики статистики',
            },
        ),
        migrations.AlterModelOptions(
            name='skillbyyear',
            options={'ordering': ('-year_statistics',), 'verbose_name': 'Статистика по навыку за определенный год', 'verbose_name_plural': 'Статистики по навыкам за определенный год'},
        ),
    ]
