# Generated by Django 4.1.5 on 2023-01-18 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_statisticsgraph_alter_skillbyyear_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillByAllYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество повторений навыка за все время')),
                ('name_skill', models.CharField(max_length=50, verbose_name='Название навыка')),
                ('statistics_graph', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills_by_all_years', to='main.statisticsgraph', verbose_name='Название графика')),
            ],
            options={
                'verbose_name': 'Ститистика по навыку за все время',
                'verbose_name_plural': 'Ститистики по навыкам за все время',
                'ordering': ('count',),
            },
        ),
    ]
