# Generated by Django 4.1.5 on 2023-01-19 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_sharevacanciesbyarea_levelsalariesbyarea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicsnumbervacanciesbyyears',
            name='statistics_graph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dynamics_num_vacancies', to='main.statisticsgraph', verbose_name='Название графика'),
        ),
        migrations.AlterField(
            model_name='dynamicsnumbervacanciesbyyearsselectedprofession',
            name='statistics_graph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dynamics_num_vacancies_sp', to='main.statisticsgraph', verbose_name='Название графика'),
        ),
        migrations.AlterField(
            model_name='dynamicssalarybyyears',
            name='statistics_graph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dynamics_salaries', to='main.statisticsgraph', verbose_name='Название графика'),
        ),
        migrations.AlterField(
            model_name='dynamicssalarybyyearsselectedprofession',
            name='statistics_graph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dynamics_salaries_sp', to='main.statisticsgraph', verbose_name='Название графика'),
        ),
        migrations.AlterField(
            model_name='levelsalariesbyarea',
            name='statistics_graph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_salaries_by_area', to='main.statisticsgraph', verbose_name='Название графика'),
        ),
        migrations.AlterField(
            model_name='sharevacanciesbyarea',
            name='statistics_graph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_vacancies_by_area', to='main.statisticsgraph', verbose_name='Название графика'),
        ),
        migrations.AlterField(
            model_name='skillbyallyear',
            name='statistics_graph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills_by_all_years', to='main.statisticsgraph', verbose_name='Название графика'),
        ),
    ]
